steps:
- id: 'kustomize'
  name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/bin/sh
    docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/docker/kustomize:v5.4.2 -f- . <<EOF
    FROM curlimages/curl AS build

    RUN set -ex; \
      curl -fL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz | tar xz && \
      chmod +x kustomize

    FROM alpine:3.16.0
    COPY --from=build /home/curl_user/kustomize /usr/local/bin/kustomize
    EOF

    docker push us-central1-docker.pkg.dev/$PROJECT_ID/docker/kustomize:v5.4.2
  waitFor: ['-']

- id: 'alpine-yarn-node:22'
  name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/bin/sh
    docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/docker/alpine-yarn-node:22 -f- . <<EOF
    FROM node:22-alpine3.18
    RUN corepack enable && yarn set version berry
    WORKDIR /srv/app
    EOF

    docker push us-central1-docker.pkg.dev/$PROJECT_ID/docker/alpine-yarn-node:22
  waitFor: ['-']

- id: 'gosec'
  name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/bin/sh
    docker build -t us-central-docker.pkg.dev/$PROJECT_ID/docker/gosec:vv -f- . <<EOF
    FROM golang:1.22-alpine
    RUN wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.20.0
    ENTRYPOINT ["./bin/gosec"]
    CMD ["-quiet", "./..."]
    EOF

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
