steps:
# use this instead of securego/gosec due to frequency of golang updates
- id: securego/gosec
  name: golang:1.22-alpine
  script: |
    #!/bin/sh
    cd src
    wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.20.0
    echo "running gosec..."
    ./bin/gosec -quiet ./...
  waitFor: ['-']

- id: semgrep
  name: semgrep/semgrep
  script: |
    #!/bin/sh
    cd src
    semgrep scan --error
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
