steps:
# use this instead of securego/gosec due to frequency of golang updates
- id: securego/gosec
  name: golang:1.22-alpine
  name: 'us-central1-docker.pkg.dev/chatparser/docker/gosec:latest'
  waitFor: ['-']

- id: semgrep/code
  name: semgrep/semgrep
  args: ['semgrep', 'scan', '--oss-only', '--error', '--quiet']
  env:
  - 'SEMGREP_SRC_DIRECTORY=/workspace'
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
