steps:
# use this instead of securego/gosec due to frequency of golang updates
- id: securego/gosec
  name: golang:1.22-alpine
  script: |
    #!/bin/sh
    cd src
    wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.20.0
    echo "running gosec..."
    ./bin/gosec -quiet ./...
  waitFor: ['-']

- id: semgrep/code
  name: semgrep/semgrep
  script: |
    #!/bin/sh
    cd src
    # configs found here https://semgrep.dev/explore
    semgrep scan --error --text --metrics=auto --verbose --config p/default --config p/secure-defaults --config p/cwe-top-25 --config p/owasp-top-ten --config p/golang --config p/javascript --config p/react --config p/eslint --config p/dockerfile --config p/docker-compose --config p/kubernetes --config p/terraform
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
