steps:
# use this instead of securego/gosec due to frequency of golang updates
- id: securego/gosec
  name: golang:1.22-alpine
  script: |
    #!/bin/sh
    cd src
    wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.20.0
    echo "running gosec..."
    ./bin/gosec -quiet ./...
  waitFor: ['-']

- id: semgrep/code
  name: semgrep/semgrep
  script: |
    #!/bin/sh
    cd src
    # configs found here https://semgrep.dev/explore
    PACKS="
      p/default,p/cwe-top-25,p/owasp-top-ten,p/secure-defaults,
      p/golang,
      p/javascript,p/react,p/eslint,
      p/dockerfile,p/docker-compose,
      p/kubernetes,p/terraform
    "

    semgrep scan --error --text --metrics=off --config=$PACKS
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
