steps:
- name: golang:1.22-alpine
  script: |
    #!/bin/sh
    cd src
    go test -timeout 1m -v ./...
  env:
  - 'GEMINI_API_KEY=fake-gemini-api-key'
  waitFor: ['-']

- name: node:22-alpine3.18
  script: |
    #!/bin/sh
    cd src/web
    yarn install
    yarn test
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
