steps:
- name: golang:1.22
  entrypoint: /bin/bash
  args:
    - -c
    - |
      go fmt src/
      test -z $(go fmt src/)
- name: hashicorp/terraform:1.9.0
  entrypoint: /bin/bash
  args:
    - -c
    - |
      terraform fmt -recursive terraform
      test -z $(terraform fmt -recursive terraform)

options:
  logging: CLOUD_LOGGING_ONLY
