steps:
- name: golang:1.22
  script: |
    #!/bin/sh
    cd src
    gofmt -d -s .
    test -z $(gofmt -d -s .)
- name: hashicorp/terraform:1.9.0
  script: |
    #!/bin/sh
    cd terraform
    terraform fmt -recursive .
    test -z $(terraform fmt -recursive .)

options:
  logging: CLOUD_LOGGING_ONLY
