apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatparser-app-
  # Project Number
  #namespace: 'project_number'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/description: 'HTTP Service for handling request to chatparser'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 20
      serviceAccountName: CLOUDRUN_SA
      containers:
      - name: chatparser
        image: chatparser
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 10
          httpGet:
            path: /healthcheck
  traffic:
  - percent: 100
    latestRevision: true
