apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatparser-app-
  # Project Number
  #namespace: 'project_number'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/description: 'HTTP Service for handling request to chatparser'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 20
      serviceAccountName: CLOUDRUN_SA
      containers:
      - name: chatparser
        image: chatparser
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: GEMINI_API_KEY
        # using an existing secret so not to incur additional cloud costs
        # and is okay as it's internal only and rotation doesn't impose risk
        - name: SIGNATURE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: GEMINI_API_KEY
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        # comenting this out for now because the startup latency is 1.12s
        # this displays a 1sec imposed delay from the first failed healthcheck and the retry
        #startupProbe:
        #  timeoutSeconds: 1
        #  periodSeconds: 1
        #  failureThreshold: 1
        #  httpGet:
        #    path: /healthcheck
  traffic:
  - percent: 100
    latestRevision: true
