steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=src/Dockerfile
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/docker/chatparser
  - --cache=true
  - --cache-ttl=6h
options:
  logging: CLOUD_LOGGING_ONLY
