services:
  chatparser:
    build:
      context: src
      target: builder
    volumes:
      - ./src:/app  # Mount current directory as /app in the container (for code changes)
    command: ["fresh"]
    environment:
      GO_ENV: development
      PORT: ${PORT}
      GEMINI_API: ${GEMINI_API}
    ports:
      - "${PORT}:${PORT}"
  terraform:
    build: terraform
    volumes:
      - ./terraform:/workspace
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      IMPERSONATE_SERVICE_ACCOUNT: ${IMPERSONATE_SERVICE_ACCOUNT}
    working_dir: /workspace/envs
    entrypoint: /bin/bash
    # prevent this from running with `docker-compose up`
    profiles:
      - terraform
