services:
  chatparser:
    build:
      context: .
      target: builder
    volumes:
      - .:/app  # Mount current directory as /app in the container (for code changes)
    command: ["fresh"]
    environment:
      GO_ENV: development
      PORT: ${PORT}
      GEMINI_API: ${GEMINI_API}
    ports:
      - "${PORT}:${PORT}"
